AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-music-directory

  Sample SAM Template for sam-music-directory

Globals:
  Function:
    Timeout: 20

Resources:
  MusicDirectoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MusicDirectoryFunction
      Handler: musicDirectory.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        MusicDirectory:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for MusicDirectory function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MusicDirectoryFunction:
    Description: "MusicDirectoryFunction Lambda ARN"
    Value: !GetAtt MusicDirectoryFunction.Arn
  MusicDirectoryFunctionIamRole:
    Description: "Implicit IAM Role created for MusicDirectory function"
    Value: !GetAtt MusicDirectoryFunctionRole.Arn