package modal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;

public class Artist {
    public String id;
    public String name;
    public String url;

    public Artist() {
    }

    public Artist(String id, String name, String url) {
        this.id = id;
        this.name = name;
        this.url = url;
    }
}
